---
title: "Planificación"
sidebar: false
toc: false
page-layout: full
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

## Forma general de funcionamiento

Este curso se compone de tres actividades principales a la semana:

-   <i class="fas fa-chalkboard-teacher"></i> [**Clases lectivas presenciales**](): los viernes de 10:15 a 11:45, donde en base a las lecturas correspondientes a esa semana se presentará un resumen de los contenidos principales y se resolverán dudas.

-   <i class="fas fa-user-edit"></i> [**Talleres prácticos**](): Actividades a ser desarrolladas de manera autónoma por l_s estudiantes durante la semana

-   <i class="fas fa-book-reader"></i> [**Lecturas**](): cada sesión lectiva tiene una lectura obligatoria asignada a la semana, la que se encuentra a disposición en esta página.

<br>

+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            |        | # <i class="fas fa-chalkboard-teacher"></i>                                                                                              | # <i class="fas fa-book-reader"></i>                                                                                      | # <i class="fas fa-user-edit"></i>                                                                                         |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
| Agosto     | 11     | [**Introducción**](/content/01-content.html)                                                                                             | [Coleman 1986](/files/readings/coleman1986.pdf)                                                                           | Leer el [programa del curso](/syllabus.html)                                                                               |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            | 18     | [**Bases: Realizar el práctico 1 de manera autónoma**](/content/02-content.html) **(no hay sesión de clases esta semana**                | [Finch cap. 1](/files/readings/finch_etal%202014cap123.pdf)                                                               | [Práctico 1: Preparación de datos con R](/assignment/01-practico.html)                                                     |        |
|            |        |                                                                                                                                          |                                                                                                                           |                                                                                                                            |        |
|            |        |                                                                                                                                          | [Moore: Comprensión de los datos](https://multivariada.netlify.app/docs/lecturas/moore_comprensiondelosdatos.pdf)         |                                                                                                                            |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            | 25     | [Estimación con distintos niveles](/content/03-content.html)                                                                             | [Finch cap. 2](/files/readings/finch_etal%202014cap123.pdf)                                                               | [Práctico 2: Estimando a distintos niveles](/assignment/02-practico.html)                                                  |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
| Septiembre | 01     | [Correlación intra clase y estimación MLM](/content/04-content.html)                                                                     | [Finch cap. 3](/files/readings/finch_etal%202014cap123.pdf)                                                               | [Práctico 3: Estimación multinivel con lmer](/assignment/03-practico.html)                                                 |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            | 08     | [Ajuste y Reporte](/content/05-content.html)                                                                                             | [O'Conell & McCoach 7, Evaluating model fit and adequacy](https://multinivel.netlify.app/readings/OConnellchap7.pdf)      | [Practico 4: Combinando datos de distintos niveles](/assignment/04-practico.html)                                          |        |
|            |        |                                                                                                                                          |                                                                                                                           |                                                                                                                            |        |
|            |        |                                                                                                                                          | [O'Conell & McCoach 11, Reporting results from multilevel](https://multinivel.netlify.app/readings/OConnellchap8.pdf)     |                                                                                                                            |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            | 15     | Semana de pausa                                                                                                                          |                                                                                                                           |                                                                                                                            |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            | 22     | Semana de asesoría, inscripciones [aquí](https://docs.google.com/spreadsheets/d/1m98s_P7n__ddbyx7C21--9N4w6ZP1t-RDlizuOTArpo/edit#gid=0) |                                                                                                                           |                                                                                                                            |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            | 28     | Entrega trabajo 1                                                                                                                        |                                                                                                                           |                                                                                                                            |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            | 29     | [Efectos Aleatorios](/content/06-content.html)                                                                                           |                                                                                                                           | [Practico 5: Efectos aleatorios](/assignment/05-practico.html)                                                             |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
| Octubre    | 6      | Ronda de presentaciones grupales                                                                                                         |                                                                                                                           |                                                                                                                            |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            | 13     | [Interacción entre niveles](/content/08-content.html)                                                                                    | [Aguinis et al (2013) Best practices MLM interactions](https://multinivel.netlify.app/readings/aguinis2013crosslevel.pdf) | [Práctica 6: Interacciones entre niveles](/assignment/06-practico.html)                                                    |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            | 20     | [Centrado](/content/09-content.html)                                                                                                     | [Enders & Tofighi 2007) Centering predictor variables MLM](https://multinivel.netlify.app/readings/enderstofighi.pdf)     | [Práctico 7: Centrado](https://commresearch.arizona.edu/classes/comm640/640_Book/docs/centering-in-multilevel-models.html) |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            | 27     | Feriado                                                                                                                                  |                                                                                                                           |                                                                                                                            |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
| Noviembre  | 3      | Semana de trabajo autónomo                                                                                                               |                                                                                                                           | Práctico 8: Reporte                                                                                                        |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            | 10     | [Extensiones](../docpres/09_extensiones/09extensiones.html)                                                                              | [Catching Up on Multilevel Modeling](https://www.annualreviews.org/doi/10.1146/annurev-psych-020821-103525)               | Praćtico 9: Extensiones                                                                                                    |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            | 17     | Presentación de trabajos                                                                                                                 |                                                                                                                           |                                                                                                                            |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
|            | 24     | Presentación de trabajos                                                                                                                 | Entrega trabajo final                                                                                                     |                                                                                                                            |        |
+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------+
