---
title: "Recursos"
website:
  comments:
    giscus:
      repo: cursos-metodos-facso/multinivel
---

En esta sección se irán subiendo una serie de recursos relacionados con el curso.

## Artículos de investigación que utilizan metodología multinivel en ámbitos asociados a sociología

- [Fuentes-Balderrama, J., Rivera-Heredia (2022). Factores personales, contextuales y académicos asociados a la reprobación en educación superior: Una muestra nacional mexicana. Revista mexicana de investigación educativa, 27(95), 1039–1062.
](https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S1405-66662022000401039&lang=es)

- [Chacón Espejo, S. K., Paredes Araya, D., Chacón Espejo, S. K., & Paredes Araya, D. (2015). Desigualdad espacial de ingresos en Chile y su relación con la concentración de capital humano. El trimestre económico, 82(326), 351–377.
](https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S2448-718X2015000200351&lang=es)



## Reporte

- [Tablas con R, con ejemplo de canciones de Spotify](https://felixanalytix.medium.com/how-to-make-beautiful-tables-using-r-programming-35d75cc919fb)

- [Introduction to Quarto](https://www.youtube.com/watch?v=_f3latmOhew)

## Uso de R

- [Conocimientos básicos de programación en R](https://descriptiva-facso.netlify.app/content/02-content)

- [Importar datos en R](https://descriptiva-facso.netlify.app/resource/03-resource) 

- [Procesamiento y análisis de datos en R (tidyverse)](https://descriptiva-facso.netlify.app/content/05-content)

- [Procesamiento y análisis de datos en R (base)](https://descriptiva-facso.netlify.app/resource/04-resource)

- [Más para aprender R](https://descriptiva-facso.netlify.app/resource/02-resource)


## Visualización

- [Visualización descriptiva de datos en R](https://descriptiva-facso.netlify.app/content/06-content)

- [R Graph Gallery](https://r-graph-gallery.com/) 

## Bases de datos

### Comparativas internacionales

- [World Values Survey](https://www.worldvaluessurvey.org/wvs.jsp)

- [ISSP](https://issp.org/)

- [ESS](https://www.europeansocialsurvey.org/)

- [LAPOP](https://www.vanderbilt.edu/lapop/index.php/)

- [Latinobarómetro](https://www.latinobarometro.org/lat.jsp)

- [ICILS: International Computer and Information Literacy Study](https://www.iea.nl/studies/iea/icils)


### Nacionales

- [Encuestas CEP](https://www.cepchile.cl/encuestaCEP)

- [ELSOC](https://dataverse.harvard.edu/dataverse/elsoc)

- [CASEN](http://observatorio.ministeriodesarrollosocial.gob.cl/encuesta-casen)

- [ENE](https://www.ine.gob.cl/estadisticas/sociales/mercado-laboral/ocupacion-y-desocupacion)

- [ESI](https://www.ine.gob.cl/estadisticas/sociales/ingresos-y-gastos/encuesta-suplementaria-de-ingresos)

- [ENCLA](https://www.ine.gob.cl/estadisticas/sociales/mercado-laboral/condiciones-de-empleo-y-relaciones-laborales)

- [ENUT](https://www.ine.cl/estadisticas/sociales/genero/uso-del-tiempo)

- [Estudios PNUD](https://www.estudiospnud.cl/)

- [EANNA](http://observatorio.ministeriodesarrollosocial.gob.cl/eanna-2012)

### Internacionales

- [ILO](https://www.ilo.org/shinyapps/bulkexplorer55/?lang=es&segment=&id=STR_DAYS_ECO_RT_A)

- [WID](https://wid.world/)

- [SWIID](https://fsolt.org/swiid/swiid_source/)

- [ICTWSS](https://www.ictwss.org/)

- [OECD](https://data.oecd.org/)

- [Banco Mundial](https://databank.worldbank.org/)


# Foro

<script src="https://giscus.app/client.js"
        data-repo="cursos-metodos-facso/multinivel"
        data-repo-id="MDEwOlJlcG9zaXRvcnkyMDA3MTE2MDk="
        data-category="Q&A"
        data-category-id="DIC_kwDOC_aduc4CYhjI"
        data-mapping="title"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="light"
        data-lang="es"
        crossorigin="anonymous"
        async>
</script>




